name: Bootcamp 2020 React Tutorial

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        version: 12
        
    - name: GitHub Action for Yarn
      # You may pin to the exact commit or the version.
      # uses: Borales/actions-yarn@fdf0082f8938ca4193f000342661784eb8e11f6a
      uses: Borales/actions-yarn@v3
      with:
        # Yarn command
        cmd: install # npm install / yarn install 
    
    - name: Creating Build
      run: sudo yarn build
      
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy Surge
      run: surge ./build https://bootcamp2020-react-tutorial.surge.sh/ --token ${{ secrets.SURGE_APP_TOKEN }}
